# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-executables-have-shebangs
        language: python
        files: \.py$

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
    -   id: ruff
        # https://docs.astral.sh/ruff/formatter/#sorting-imports
        args: [check, --select, I, --fix]
        name: ruff-isort

    -   id: ruff-format

    -   id: ruff
