# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-executables-have-shebangs
        language: python
        files: \.py$

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
    -   id: ruff-check
        # https://docs.astral.sh/ruff/formatter/#sorting-imports
        args: [check, --select, I, --fix]
        name: ruff-isort
    -   id: ruff-format
    -   id: ruff-check
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies: ["types-netaddr>=1.3.0.20251108","types-pexpect>=4.9.0.20250916","types-requests>=2.32.4.20250913"]
